Golangci-lint integration and errors fixes
mattermost/mattermost-plugin-skype4business pull request #72
Opened 2020-10-09 15:24 UTC by AugustasV

Summary
#55 Integrate GoLangici-lint and fix most of linter errors.

#### Ticket Link

  Integrate GolangCI lint https://github.com/mattermost/mattermost-plugin-skype4business/issues/55

2020-10-09 15:24 UTC, mattermod commented
Hello @AugustasV,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-09 17:17 UTC, hanzei approved these changes
Nice, thanks for migrating also this plugin :+1:

2020-10-20 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-20 20:40 UTC, jasonblais commented
@mickmister @kosgrz kind reminder to help with a review :)

2020-10-21 01:00 UTC, mickmister approved these changes
LGTM, thanks @AugustasV! I have one request on changing spelling of `custome` -> `custom`

There are some merge conflicts from my PR that sync'd this repo with the starter template. Let me know if you have any trouble resolving the conflicts

2020-10-25 14:09 UTC, AugustasV commented
@hanzei @mickmister done, conflicts solved.

2020-10-27 16:17 UTC, hanzei requested changes
Two things got mixed in the Merge

2020-10-27 16:17 UTC, hanzei commented on Makefile
> +
That seems like an unrelated change.

2020-10-27 16:17 UTC, hanzei commented on go.mod
> +	github.com/google/go-cmp v0.5.2 // indirect
Could you please remove the `indirect` dependencies?

2020-11-02 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-02 17:04 UTC, jfrerich commented
Hi @AugustasV, how are things going with this PR?  Do you have any questions or need any help addressing the feedback from @hanzei?

2020-11-03 09:23 UTC, hanzei approved these changes
Build tests locally and does deploy correctly. LGMT :+1:

2020-11-03 09:23 UTC, hanzei commented
Skipping QA review as these are only build changes

2020-11-03 09:23 UTC, merged