[GH-61]:Use SiteURL for all calls from the webapp
mattermost/mattermost-plugin-skype4business pull request #93
Opened 2022-12-30 11:26 UTC by Kshitij-Katiyar

**Summary** 

- Used site URL for all the API calls from the webapp to the server.
- This PR is an extension from PR:- https://github.com/mattermost/mattermost-plugin-skype4business/pull/78

- [Issue #61](https://github.com/mattermost/mattermost-plugin-skype4business/issues/61)

2022-12-30 11:26 UTC, mattermod commented
Hello @Kshitij-Katiyar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-01-10 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-02-01 13:52 UTC, javaguirre requested changes
Thank you! some small details.

2023-02-01 13:52 UTC, javaguirre commented on webapp/src/client/client.js
> +        this.url = url + `/plugins/${pluginID}/api/v1`;
```suggestion
        this.url = `${url}/plugins/${pluginID}/api/v1`;
```

2023-02-01 13:52 UTC, javaguirre commented on webapp/src/selectors/index.js
> +    if (config && config.SiteURL) {
can't you do `config?.SiteURL` ?

2023-02-01 13:52 UTC, javaguirre commented on webapp/src/selectors/index.js
> +            basePath = basePath.substr(0, basePath.length - 1);
`basePath.replace(/\/$/, "");` is more straight forward IMO.

2023-02-06 08:43 UTC, javaguirre approved these changes
Great work

2023-02-15 14:43 UTC, hanzei commented
/update-branch

2023-02-15 14:43 UTC, mattermost-build commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2023-02-15 14:44 UTC, hanzei commented
@Kshitij-Katiyar Would you please merge `master` into your branch?

2023-02-15 14:53 UTC, Kshitij-Katiyar commented
> @Kshitij-Katiyar Would you please merge `master` into your branch?

@hanzei synced with the master

2023-02-15 16:46 UTC, mickmister approved these changes

2023-02-21 11:52 UTC, hanzei commented
@DHaussermann Would you mind testing the PR in release testing?

2023-03-04 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-03-21 19:58 UTC, merged